services:
  web:
    image: php:8.2-apache
    container_name: dmx_web
    ports:
      - "8082:80"
    volumes:
      - ./public:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - dmx_network

  db:
    image: mysql:8.0
    container_name: dmx_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dmx
      MYSQL_USER: dmx_user
      MYSQL_PASSWORD: dmx_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dmx_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dmx_phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - dmx_network

networks:
  dmx_network:
    driver: bridge

volumes:
  mysql_data:
